# tasks/sublime3_install.yml (Correct structure for inclusion)
---
# --------------------------------------------------------------------------
# 1. DEBIAN / UBUNTU PATH (Installs .deb file)
# --------------------------------------------------------------------------
- name: Download .deb package (Debian/Ubuntu)
  ansible.builtin.get_url:
    url: "{{ sublime_text_3_urls.deb_url }}"
    dest: "{{ sublime_text_3_urls.deb_dest }}"
    validate_certs: no
  when: ansible_os_family == 'Debian'

- name: Install Sublime Text 3 from local .deb file
  ansible.builtin.apt:
    deb: "{{ sublime_text_3_urls.deb_dest }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Clean up .deb file
  ansible.builtin.file:
    path: "{{ sublime_text_3_urls.deb_dest }}"
    state: absent
  when: ansible_os_family == 'Debian'

# --------------------------------------------------------------------------
# 2. REDHAT / FEDORA PATH (Installs .rpm file)
# --------------------------------------------------------------------------
- name: Download .rpm package (RedHat/Fedora)
  ansible.builtin.get_url:
    url: "{{ sublime_text_3_urls.rpm_url }}"
    dest: "{{ sublime_text_3_urls.rpm_dest }}"
    validate_certs: no
  when: ansible_os_family == 'RedHat'

- name: Install Sublime Text 3 from local .rpm file
  ansible.builtin.dnf:
    name: "{{ sublime_text_3_urls.rpm_dest }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Clean up .rpm file
  ansible.builtin.file:
    path: "{{ sublime_text_3_urls.rpm_dest }}"
    state: absent
  when: ansible_os_family == 'RedHat'