---
- name: Configure Linux dev machine for my usage
  hosts: all
  become: yes

  vars_files:
    # Load the variables at the play level
    - vars/sublime3_vars.yml

  tasks:
    - name: Install packages from packmgr_packages directory with default package manager
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ lookup('ansible.builtin.fileglob', 'packmgr_packages/*.yml', wantlist=True) }}"
      loop_control:
        # Optional: Makes the output cleaner by showing the file name being included
        label: "Including {{ item | ansible.builtin.basename }}"

    # Check whether flatpak is installed
    - name: Ensure 'flatpak' package manager is installed
      ansible.builtin.package:
        name: flatpak
        state: present

    - name: Add the Flathub remote repository (system-wide)
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        state: present
        method: system

    - name: Install packages from flatpak_packages directory with flatpak
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ lookup('ansible.builtin.fileglob', 'flatpak_packages/*.yml', wantlist=True) }}"
      loop_control:
        # Optional: Makes the output cleaner by showing the file name being included
        label: "Including {{ item | ansible.builtin.basename }}"

    - name: Run version-specific Sublime Text 3 installation tasks
      # Import the tasks list. Variables are already available via vars_files.
      ansible.builtin.import_tasks: other_packages/sublime3.yml
