---
- name: Configure Linux dev machine for my usage
  hosts: all
  become: yes

  tasks:
    - name: Install packages from packmgr_packages directory with default package manager
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ lookup('ansible.builtin.fileglob', 'packmgr_packages/*.yml', wantlist=True) }}"
      loop_control:
        # Optional: Makes the output cleaner by showing the file name being included
        label: "Including {{ item | ansible.builtin.basename }}"

